---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cadency.fullname" . }}-config
  labels:
    {{- include "cadency.labels" . | nindent 4 }}
data:
  logLevel: {{ .Values.cadency.logLevel }}