---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cadency.fullname" . }}-secrets
  labels:
    {{- include "cadency.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.cadency.discordToken | b64enc }}